function(add_extractor name)
    add_executable(${name} ${name}.c)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${name}.txt")
        target_sources(${name} PRIVATE "${name}.txt")
        install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/${name}.txt" DESTINATION ${CMAKE_INSTALL_DOCDIR})
    endif()
    target_folder(${name} "Extractors")
    install(TARGETS ${name} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endfunction()

add_subdirectory(backup)
add_subdirectory(ckabstape)
add_subdirectory(cpytap)
add_subdirectory(dbtap)
add_subdirectory(libvhd)
add_subdirectory(mmdir)
add_subdirectory(mtdump)
add_subdirectory(ods2)
add_subdirectory(rawcopy)
add_subdirectory(rawtap)
add_subdirectory(rstsflx)
add_subdirectory(sdsdump)
add_subdirectory(tapeio)
add_subdirectory(tpdump)
if(NOT WIN32)
    add_subdirectory(vhd-util)
endif()
