.TH MACRO7 1 "April 12, 1996" "Version 3.0" "PDP-7 Assembler Manual"
.SH NAME
macro7 \- a PDP-7 assembler

.SH SYNOPSIS
.B macro7
[ -d -p -m -r -x ] inputfile inputfile...

.SH DESCRIPTION
This is a cross-assembler for PDP-7 assembly language programs. It produces
an output file in RIM format only. A listing file is always produced, with
optional symbol table and/or symbol cross-reference (concordance). The
permanent symbol table can be output in a form that may be read back in,
allowing for a customized permanent symbol table. Any detected errors are
output to a separate file, including the filename, line number, column
number, and error message, as well as marking the error in the listing file.

The following file name extensions are used:
.TP
.B .7
source code (input)
.TP
.B .lst
assembly listing (output)
.TP
.B .rim
assembly output in DEC's RIM format (output)
.TP
.B .err
assembly errors detected (if any) (output)
.TP
.B .prm
permanent symbol table in a form suitable for reading after the EXPUNGE
pseudo-op.

.SH OPTIONS
.TP
.B -d
Dump the symbol table at the end of assembly.
.TP
.B -p
Generate a file with the permanent symbols in it.
(To get the current symbol table, assemble a file that has only START in it.)
.TP
.B -x
Generate a cross-reference (concordance) of user symbols.

.SH DIAGNOSTICS
Assembler error diagnostics are output to an error file and inserted in the
listing file. Each line in the error file has the form:
.nf
<filename>(<line>:<col>) : error: <message> at Loc = <loc>
.fi

An example error message is:
.nf
bintst.7(17:9) : error: undefined symbol "UNDEF" at Loc = 07616
.fi

The error diagnostics in the listing start with a two-character error code
(if appropriate) and a short message. A caret '^' is placed under the item
in error if appropriate. An example error message is:
.nf
17 07616 3000          DAC     UNDEF
UD undefined                  ^
18 07617 1777          TAD  I  DUMMY
.fi

When an indirect is generated, an at character '@' is placed after the
instruction value in the listing as an indicator as follows:
.nf
14 03716 1777@         TAD     OFFPAG
.fi

Undefined symbols are marked in the symbol table listing by prepending a
'?' to the symbol. Redefined symbols are marked in the symbol table listing
by prepending a '#' to the symbol. Examples are:
.nf
#REDEF   04567
 SWITCH   07612
?UNDEF   00000
.fi

Refer to the code for the diagnostic messages generated.

.SH REFERENCES
This assembler is based on the PAL assembler by:
Douglas Jones <jones@cs.uiowa.edu> and
Rich Coon <coon@convexw.convex.com>

.SH COPYRIGHT
This is free software. There is no fee for using it. You may make any
changes that you wish and also give it away. If you can make a commercial
product out of it, fine, but do not put any limits on the purchaser's right
to do the same. If you improve it or fix any bugs, it would be nice if you
told me and offered me a copy of the new version.

.SH AMENDMENTS
.TP
.B Version 1.0 (12Apr96)
Original.
.TP
.B Version 1.1 (18Nov96)
Permanent symbol table initialization error.
.TP
.B Version 1.2 (20Nov96)
Added BINPUNch and RIMPUNch pseudo-operators.
.TP
.B Version 1.3 (24Nov96)
Added DUBL pseudo-op (24-bit integer constants).
.TP
.B Version 1.4 (29Nov96)
Fixed bug in checksum generation.
.TP
.B Version 2.1 (08Dec96)
Added concordance processing (cross-reference).
.TP
.B Version 2.2 (10Dec96)
Added FLTG pseudo-op (floating point constants).
.TP
.B Version 2.3 (02Feb97)
Fixed paging problem in cross-reference output.
.TP
.B Version 3.0 (14Feb97)
MACRO8X features.
