function(add_cross_assembler name)
    add_executable(${name} ${name}.c)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${name}.txt")
        target_sources(${name} PRIVATE "${name}.txt")
        install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/${name}.txt" DESTINATION ${CMAKE_INSTALL_DOCDIR})
    endif()
    target_folder(${name} "Cross Assemblers")
    install(TARGETS ${name} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endfunction()

add_subdirectory(hpasm)
add_subdirectory(macro1)
add_subdirectory(macro11)
add_subdirectory(macro7)
add_subdirectory(macro8x)
