name: Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        include:
          - os: macos-latest
            cp: cp
            path: /build-simtools-release/
            pkg-ext: tar.gz
          - os: ubuntu-latest
            cp: cp
            path: /build-simtools-release/
            pkg-ext: tar.gz
          - os: windows-latest
            cp: copy
            path: \build-simtools-release\
            pkg-ext: zip

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true

    #- name: Install Prerequisites Linux
    #  if: ${{matrix.os == 'ubuntu-latest'}}
    #  shell: bash
    #  env:
    #    DEBIAN_FRONTEND: noninteractive
    #  run: |
    #    ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
    #    echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
    #    sudo dpkg-reconfigure man-db

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      run: |
        cmake --version
        cmake --workflow --preset release

    # This is needed because our build directory is in ${{runner.workspace}},
    # not ${{github.workspace}} and the upload-artfact action can only source
    # files from ${{github.workspace}}.
    - name: Copy Package to Workspace
      run: |
        ${{matrix.cp}} ${{runner.workspace}}${{matrix.path}}*.${{matrix.pkg-ext}} ${{github.workspace}}

    - name: Upload Package Artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        archive: false
        path: ${{github.workspace}}/*.${{matrix.pkg-ext}}
        compression-level: 0
